"""Constants for the Eaton xComfort Bridge integration."""

from homeassistant.const import Platform

DOMAIN = "xcomfort_bridge"

PLATFORMS: list[Platform] = [
    Platform.BINARY_SENSOR,
    Platform.CLIMATE,
    Platform.COVER,
    Platform.EVENT,
    Platform.LIGHT,
    Platform.SCENE,
    Platform.SENSOR,
]

CONF_AUTH_MODE = "auth_mode"
CONF_SECRET = "secret"

AUTH_MODE_DEVICE = "device"
AUTH_MODE_USER = "user"
AUTH_MODES = {
    AUTH_MODE_USER: "User",
    AUTH_MODE_DEVICE: "Auth code",
}

DEFAULT_DEVICE_USERNAME = "default"
DEFAULT_HEARTBEAT_INTERVAL = 30
DEFAULT_READ_TIMEOUT = 90
DEFAULT_RECONNECT_MAX = 60
DEFAULT_STARTUP_TIMEOUT = 15

MESSAGE_ACK = 1
MESSAGE_HEARTBEAT = 2
MESSAGE_CONNECT_CONFIRM = 11
MESSAGE_SC_INIT = 14
MESSAGE_SC_SECRET = 16
MESSAGE_SC_ESTABLISHED = 17
MESSAGE_AUTH_LOGIN = 30
MESSAGE_AUTH_LOGIN_DENIED = 31
MESSAGE_AUTH_LOGIN_SUCCESS = 32
MESSAGE_AUTH_APPLY_TOKEN = 33
MESSAGE_AUTH_APPLY_TOKEN_RESPONSE = 34
MESSAGE_AUTH_RENEW_TOKEN = 37
MESSAGE_AUTH_RENEW_TOKEN_RESPONSE = 38
MESSAGE_INITIAL_DATA = 240
MESSAGE_HOME_DATA = 242
MESSAGE_DIAGNOSTICS = 243
MESSAGE_ACTION_SLIDE_DEVICE = 280
MESSAGE_ACTION_SWITCH_DEVICE = 281
MESSAGE_ACTIVATE_SCENE = 285
MESSAGE_ACTION_SHADING_DEVICE = 355
MESSAGE_SET_DEVICE_STATE = 291
MESSAGE_SET_ALL_DATA = 300
MESSAGE_SET_HOME_DATA = 303
MESSAGE_SET_DIAGNOSTICS = 304
MESSAGE_SET_STATE_INFO = 310
MESSAGE_SET_HEATING_STATE = 353
MESSAGE_SET_ROOM_HEATING_STATE = 363
MESSAGE_SET_BRIDGE_STATE = 364

DEVTYPE_SWITCH = 100
DEVTYPE_DIMMER = 101
DEVTYPE_SHADING = 102
DEVTYPE_PUSHBUTTON = 201
DEVTYPE_ROCKER = 220
DEVTYPE_ROOM_CONTROLLER = 450

DP_ON_OFF = "1351"

INFO_CODE_DEVICE_TEMPERATURE = "1109"
INFO_CODE_SIGNAL_STRENGTH = "1111"
INFO_CODE_RCT_TEMPERATURE = "1222"
INFO_CODE_RCT_HUMIDITY = "1223"
INFO_CODE_SUM_REQUEST = "1227"

BATTERY_CODE_MAP: dict[str, int] = {
    "1113": 0,
    "1114": 25,
    "1115": 50,
    "1116": 75,
    "1117": 100,
}
BATTERY_CODE_MAINS = "1119"

SIGNAL_LABELS: dict[str, str] = {
    "0": "Unknown",
    "1": "Excellent",
    "2": "Good",
    "3": "Fair",
    "4": "Poor",
}

CLIMATE_MODE_FROST = 1
CLIMATE_MODE_ECO = 2
CLIMATE_MODE_COMFORT = 3

CLIMATE_STATE_OFF = 0
CLIMATE_STATE_HEATING_AUTO = 1
CLIMATE_STATE_HEATING_MANUAL = 2
CLIMATE_STATE_COOLING_AUTO = 3
CLIMATE_STATE_COOLING_MANUAL = 4

CLIMATE_MODE_LABELS: dict[int, str] = {
    CLIMATE_MODE_FROST: "Frost protection",
    CLIMATE_MODE_ECO: "eco",
    CLIMATE_MODE_COMFORT: "comfort",
}

COMPTYPE_DOOR_WINDOW_SENSOR = 76
DOOR_WINDOW_MODE_DOOR = "1310"

LIGHT_DEVICE_TYPES = {DEVTYPE_SWITCH, DEVTYPE_DIMMER}
COVER_DEVICE_TYPES = {DEVTYPE_SHADING}
EVENT_DEVICE_TYPES = {DEVTYPE_PUSHBUTTON, DEVTYPE_ROCKER}

SHADE_OP_OPEN = 0
SHADE_OP_CLOSE = 1
SHADE_OP_STOP = 2
SHADE_OP_GO_TO = 5

# Device usage values that indicate heating/cooling capability (APK Dn enum).
USAGE_HEATING: frozenset[int] = frozenset({2, 22, 23, 25, 101, 102})
USAGE_COOLING: frozenset[int] = frozenset({21, 22, 24, 25, 101, 102})
